name: Run dockerdesktop
on:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  docker_runner:
    env:
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Update components
      run: |
        sudo timedatectl set-timezone Asia/Manila
        sudo dpkg --add-architecture i386
        sudo sed -i 's|http://azure.|http://|g' /etc/apt/apt-mirrors.txt
        sudo sed -i 's|http://azure.|http://|g' /etc/apt/sources.list
        sudo chmod 0644 /boot/vmlinuz*
        sudo chmod +r /boot/vmlinuz-*
        sudo apt-get update && sudo apt-get install curl python3 python3-pip libsm6 cabextract wimtools chntpw genisoimage setools lzip wine wine32 wine64 winetricks patchelf e2fsprogs aria2 unzip attr whiptail binutils zstd p7zip-full wget apt-transport-https software-properties-common
        source /etc/os-release
        wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
        echo 'export PATH="'"$(python3 -m site --user-base)"'/bin:$PATH"' >> ~/.bashrc
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        python -m pip install --upgrade pip
        export DOWNLOAD_URL="https://mirrors.bfsu.edu.cn/docker-ce"
        curl -fsSL https://get.docker.com/ | sh
        
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        ref: ${{ github.head_ref }}

    - name: Deploy docker-compose
      run: |
        docker-compose up --build
        
    - name: View directory
      run: |
        ls -alh
        
