name: Github-Remote-Desktop

on: workflow_dispatch

jobs:
  runner:
    env:
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Add registry settings
      run: |
        $DesktopDir = "$($env:USERPROFILE)\Desktop"
        $filepath1 = "$($env:USERPROFILE)\Desktop\Ragnarok_X_installer01.zip"
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\AppVeyor\Build Agent\State" /V GetSources /T REG_SZ /D true /F
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v HideFileExt /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSuperHidden /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v Hidden /t REG_DWORD /d 1 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSecondsInSystemClock /t REG_DWORD /d 1 /f
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok-v3-stable-windows-amd64.zip
        Invoke-WebRequest https://download.sysinternals.com/files/SysinternalsSuite.zip -OutFile SysinternalsSuite.zip
        Invoke-WebRequest https://rox-cdn.ragnarokx.net/windows/na_publish/Ragnarok_X_installer01.zip -OutFile "$filepath1"
        7z x "Ragnarok_X_installer01.zip" -o$DesktopDir
        Invoke-WebRequest https://www.quicksfv.org/qsfv236x64.exe -OutFile "$DesktopDir\qsfv236x64.exe"
        7z x "ngrok-v3-stable-windows-amd64.zip" -ofiles
        7z x "SysinternalsSuite.zip" -ofiles
        Get-WmiObject -Class Win32_DesktopMonitor | Select-Object ScreenWidth,ScreenHeight
    - name: Enable Remote Desktop
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-in)'
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Modify config YML file for NGROK
      run: |
        cd files
        .\NGRok_run.exe
    - name: Connection details
      run: |
        7z a -tzip "tmp.zip" "../../mozilla-unified" -x!*.git -mx9 -mmt
        7z x "tmp.zip" -o"C:\_Workspace"
        erase "tmp.zip"
        cd files
        .\NGROK-CHECK.bat
    - name: Pause Build
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell
